Rust minimum version to 1.89
Required for

error[E0658]: using `_` for array lengths is unstable
   --> src/traffic.rs:388:48
    |
388 |         s.buf = SliceOrVec::Owned(Box::new([0; _]));
    |                                                ^
    |
    = note: see issue #85077 <https://github.com/rust-lang/rust/issues/85077> for more information