Update picow to new cyw43
Fixes build failures. Toolchain is updated, but we can't upgrade to
latest nightly because it fails with an ICE, possibly
https://github.com/rust-lang/rust/issues/110206

thread 'rustc' panicked at 'DefId(35:311 ~ embedded_io[99f8]::asynch::Write::write::{opaque#0}) does not have a "def_span"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:205:1